load maude/venus-lang-transition-machine.maude
load maude/venus-lang-testing.maude

mod TEST-EXTRACT is
    protecting VENUS-TS .
    protecting VENUS-TESTING .

    op pgm : -> Inst .
    eq pgm =
def 'countPositive ('n) {
    'count := 0 ;
    'i := 0 ;
    while ('i lt 'n) do
        'count := 'count + 1 ;
        'i := 'i + 1
    od
} .
endm

--- See what constants are extracted
reduce extractConstants(pgm) .
reduce genBoundaries(extractConstants(pgm)) .
reduce toIntSet(genBoundaries(extractConstants(pgm))) .
reduce 0 ;; 1 ;; toIntSet(genBoundaries(extractConstants(pgm))) .

quit
