mod VENUS-SYMBOLIC-CONDITIONALS is
    protecting VENUS-SYMBOLIC-STATE .

    vars INST1 INST2 : FInst .
    var CONDITION : BExpr .
    var DIVISOR : AExpr .
    var CONTROL : Control .
    var PATH_CONDITION : BExpr .
    var SYMBOLIC_MEMORY : SymMemory .

    crl [IfSymConditionDivisionByZero] :
        sState [ (if CONDITION then INST1 else INST2 fi) # CONTROL
               | PATH_CONDITION
               | SYMBOLIC_MEMORY ]
        =>
        sBug [ divZeroPC(PATH_CONDITION, DIVISOR, SYMBOLIC_MEMORY)
             | SYMBOLIC_MEMORY ]
        if hasDivB(CONDITION)
        /\ DIVISOR := getDivisorB(CONDITION) .
    crl [IfSymThen] :
        sState [ (if CONDITION then INST1 else INST2 fi) # CONTROL
               | PATH_CONDITION
               | SYMBOLIC_MEMORY ]
        =>
        sState [ INST1 # CONTROL
               | thenPC(PATH_CONDITION, CONDITION, SYMBOLIC_MEMORY)
               | SYMBOLIC_MEMORY ]
        if not hasDivB(CONDITION) .

    crl [IfSymThenDivisionSafe] :
        sState [ (if CONDITION then INST1 else INST2 fi) # CONTROL
               | PATH_CONDITION
               | SYMBOLIC_MEMORY ]
        =>
        sState [ INST1 # CONTROL
               | thenSafePC(PATH_CONDITION, DIVISOR, CONDITION, SYMBOLIC_MEMORY)
               | SYMBOLIC_MEMORY ]
        if hasDivB(CONDITION)
        /\ DIVISOR := getDivisorB(CONDITION) .

    crl [IfSymElse] :
        sState [ (if CONDITION then INST1 else INST2 fi) # CONTROL
               | PATH_CONDITION
               | SYMBOLIC_MEMORY ]
        =>
        sState [ INST2 # CONTROL
               | elsePC(PATH_CONDITION, CONDITION, SYMBOLIC_MEMORY)
               | SYMBOLIC_MEMORY ]
        if not hasDivB(CONDITION) .

    crl [IfSymElseDivisionSafe] :
        sState [ (if CONDITION then INST1 else INST2 fi) # CONTROL
               | PATH_CONDITION
               | SYMBOLIC_MEMORY ]
        =>
        sState [ INST2 # CONTROL
               | elseSafePC(PATH_CONDITION, DIVISOR, CONDITION, SYMBOLIC_MEMORY)
               | SYMBOLIC_MEMORY ]
        if hasDivB(CONDITION)
        /\ DIVISOR := getDivisorB(CONDITION) .
endm
