load core/venus-lang-configuration.maude
load core/venus-lang-arithmetic.maude
load core/venus-lang-boolean.maude
load core/venus-lang-instructions.maude
load core/venus-lang-functions.maude
load core/venus-lang-desugaring.maude

mod VENUS-TS is
    protecting VENUS-ARITHMETIC .
    protecting VENUS-BOOLEAN .
    protecting VENUS-INSTRUCTIONS .
    protecting VENUS-FUNCTIONS .
    protecting VENUS-DESUGARING .
endm
