load testing/venus-lang-symbolic-state.maude
load testing/venus-lang-symbolic-functions.maude
load testing/venus-lang-symbolic-structural.maude
load testing/venus-lang-symbolic-assignments.maude
load testing/venus-lang-symbolic-conditionals.maude
load testing/venus-lang-symbolic-loops.maude

mod VENUS-SYMBOLIC is
    protecting VENUS-SYMBOLIC-FUNCTIONS .
    protecting VENUS-SYMBOLIC-STRUCTURAL .
    protecting VENUS-SYMBOLIC-ASSIGNMENTS .
    protecting VENUS-SYMBOLIC-CONDITIONALS .
    protecting VENUS-SYMBOLIC-LOOPS .
endm
